"""Add evaluators table

Revision ID: 6e79f140d89b
Revises: a975a3c6c604
Create Date: 2026-09-17 20:20:32.546475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e79f140d89b'
down_revision = 'a975a3c6c604'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'EVALUATOR', name='evaluatorrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluators_email'), 'evaluators', ['email'], unique=True)
    op.create_index(op.f('ix_evaluators_id'), 'evaluators', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluators_id'), table_name='evaluators')
    op.drop_index(op.f('ix_evaluators_email'), table_name='evaluators')
    op.drop_table('evaluators')
    # ### end Alembic commands ###
